### ISSUE TITLE
Header Component. Harcoded switch mode

### ISSUE THREAD

**Issue by MateYCode** [Chabulsqu/country-finder#3]
The Header could be stateless, and in that case the App component would pass the 'mode' as an additional prop when calling it, like this: `<Header method={this.switchModes} mode={this.state.mode} />`
Then, the Header could determine, based on the received mode, what content to show. This also means that the `<App>` doesn't need to worry about keeping 'content' in its state, as Header is now handling that.
```js
export default class Header extends React.Component {
	render() {
		return (
			<header>
				<h1>Where in the world?</h1>
				<button onClick={this.props.method}>
					<div role="presentation">
						<i className={this.props.mode === 'App light' ? "fa-light fa-moon" : "fa-solid fa-moon"}></i>
						<em>{this.props.mode === 'App light' ? 'Light Mode' : 'Dark mode'}</em>
					</div>
				</button>
			</header>
		)
	}
}
```

**Comment by Chabulsqu** [comment]
Hello, last week I decided to refactor the project and saw your issue. I managed to implement most of the previous features, this time using: 
* React Function Components
* React hooks 
* Client-side routing with React Router 

However, I was surprised by the fact that the API had been shut down, so I could not keep working on the project. 

I made a new branch (experimental) that contains all the new code I wrote, although it won't work now (and neither the master branch). I guess I'll wait for someone to host the API again (._.).
